name: Create Artifact

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create artifact
      - run: echo "Hello, World!" > hello.txt
     
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./hello.txt
