name: Testing Diagnostic Logs

on:
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run another script
      run: echo Second step!
